name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    # MRE_Client steps
    - name: Install MRE_Client dependencies
      run: npm ci
      working-directory: ./MRE_Client
      
    - name: Build MRE_Client
      run: npm run build --if-present
      working-directory: ./MRE_Client
      
    - name: Test MRE_Client
      run: npm test
      working-directory: ./MRE_Client

    # MRE_Server steps
    - name: Install MRE_Server dependencies
      run: npm ci
      working-directory: ./MRE_Server
      
    - name: Build MRE_Server
      run: npm run build --if-present
      working-directory: ./MRE_Server
      
    - name: Test MRE_Server
      run: npm test
      working-directory: ./MRE_Server